"""修改confirmed字段名

Revision ID: c138d26dd002
Revises: dc7a17d762bb
Create Date: 2018-06-27 15:40:51.338543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c138d26dd002'
down_revision = 'dc7a17d762bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'comfirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
